name: Vibing Agent

on:
  schedule:
    - cron: "* * * * *"  # attempt every minute; GitHub may throttle to ~5m
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-agent:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      MODEL: gpt-4o
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r agents/requirements.txt

      - name: Run agent (LLM mode)
        run: |
          python agents/run.py --mode llm --model "$MODEL"

      - name: Compute EST timestamp for commit
        id: ts
        shell: bash
        run: |
          EST_TS=$(TZ=America/New_York date +"%Y-%m-%d %H:%M:%S EST")
          echo "est_ts=$EST_TS" >> "$GITHUB_OUTPUT"

      - name: Stage changes
        run: |
          git add docs/ agents/state.json agent-reasoning/ || true

      - name: Check for changes
        id: diff
        run: |
          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit
        if: steps.diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "chore(agent): update content — run ${{ steps.ts.outputs.est_ts }}"

      - name: Push
        if: steps.diff.outputs.changed == 'true'
        run: |
          git push origin HEAD:main


